version: '3.7'

# To run a specific version of Jaeger, use environment variable, e.g.:
#     JAEGER_VERSION=1.52 docker compose up

services:
  jaeger:
    image: jaegertracing/all-in-one:1.6
    ports:
      - "16686:16686"
      - "4318:4318"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
      - "9411:9411"
    environment:
      - LOG_LEVEL=debug
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
#    networks:
#      - jaeger-example

